common:
    database:
        scenes: all
        horz_ref: True
        patch_mode: shift_center
        color: gray
        train_size: 0.8
    model:
        model: IQA_DeepQA_FR_release.models.FR_sens_1
        ign: 4
        ign_scale: 8
        opt_scheme: adam
        lr: 1e-4
        wr_l2: 5e-3
        wr_tv: 1e-2
    training:
        batch_size: 5
        epochs: 80
        test_freq: 2
        save_freq: 1
        regular_snap_freq: 50
        n_imgs_to_record: 30
        prefix: 'FR_sens_'

fr_sens_LIVE:
    database:
        sel_data: LIVE
        dist_types: all
        patch_size: [112, 112]
    model:
        opt_scheme: nadam
        lr: 1e-4

fr_sens_CSIQ:
    database:
        sel_data: CSIQ
        dist_types: all
        # patch_size: [112, 112]
        patch_size:
    model:
        lr: 5e-4

fr_sens_TID2008:
    database:
        sel_data: TID2008
        dist_types: all
        patch_size:
        # patch_size: [112, 112]
        # patch_size:
    model:
        lr: 5e-4
        # lr: 1e-4

fr_sens_TID2013:
    database:
        sel_data: TID2013
        dist_types: all
        patch_size:
    model:
        # lr: 1e-3
        lr: 5e-4
